### ISSUE TITLE
on rare occasions, user names show as "unknown"

### ISSUE THREAD

**Issue by endofline** [hangoutsbot/hangoutsbot#102]
this issue has been discussed at length in https://github.com/tdryer/hangups/issues/4

primarily observed when adding users to a syncout/syncroom chat. there isn't a fully operational workaround for this problem yet. please report whether the affected user:
* has a g+ profile, whether the profile is incomplete in any way, etc
* uses non-google clients to connect to hangups

**Comment by nylonee** [comment]
Could we store the full name of the user in memory.json to bypass this problem?

**Comment by nylonee** [comment]
Just pushed yet another experimental branch, a workaround to issue where some users would be displayed as unknown. The workaround stores successfully retrieved full_names in memory, and calls those if they're there, otherwise it'll default back to unknown. To use it on this experimental branch, you'll need to call the get_name() function from hangupsbot.py, passing in the User object. Function [here](https://github.com/nylonee/hangupsbot/blob/nylonee/bugfix-unknown-names/hangupsbot/hangupsbot.py#L344)
Example usage [here](https://github.com/nylonee/hangupsbot/blob/nylonee/bugfix-unknown-names/hangupsbot/plugins/syncrooms.py#L134)

**Comment by endofline** [comment]
depending on the work based on hangups forks like https://github.com/endofline/hangups/tree/workaround/fallback-user, the workaround may no longer be necessary by 2.4

**Comment by endofline** [comment]
tdryer/hangups#4 has implemented `build_user_list` and a new reference pattern that uses it - this has been implemented as part of the compatibility fixes in #146

**Comment by Dahu88** [comment]
I started using it today and I had the same problem, I'm juste listed as "Unknown".
My G+ profile is https://plus.google.com/+NicolasRemyDahu
The version is 2.3.1

**Comment by endofline** [comment]
@Dahu88 you will need to pull and build latest hangups master from tdryer, along with the newly-released version of hangupsbot 2.3.2 to resolve this

**Comment by Dahu88** [comment]
@endofline thanks I'll bring this info to my fellow admin.

**Comment by endofline** [comment]
This issue should have been solved by [Permanent Memory](https://github.com/hangoutsbot/hangoutsbot/wiki/Permanent-Memory) around 2.6 (re: #248). If this occurs again, please re-open this issue :)
