### ISSUE TITLE
Implementing 'roles', and user-defined roles

### ISSUE THREAD

**Issue by nylonee** [hangoutsbot/hangoutsbot#121]
Some discussion today regarding having the ability to add more roles beyond 'admin' (and botkeeper).

Initial thoughts on implementing this involved having user-defined roles that admins can set, and they choose which plugins those users have access to.

Opening this issue for discussion and thoughts.

**Comment by endofline** [comment]
since we are already maintain a [user memory](https://github.com/nylonee/hangupsbot/wiki/%60bot%60-functions-for-developers#settingretrieving-memory), we could implement tag-based role assignment to users which plugin developers can optionally use if they require greater permission variety than just user, admin and botkeeper

**Comment by Riptides** [comment]
but if the plugin had commands which required a specific tag to run wouldn't they still show up in /bot help under the user category potentially causing confusion to those who couldn't use them?

**Comment by endofline** [comment]
personally, i rather have minimal changes in the actual core framework code as it stands for reasons of simplicity and debugging. the includes the `/bot help` command since its one of the few commands that doesn't require a plugin to implement...

that being said, we could possibly extend the `help` command to check a shared object (function or variable) via [`register_object` and `call_shared`](https://github.com/nylonee/hangupsbot/wiki/Plugin-Authoring#sharing-plugin-functionality) - the shared object could output additional details on permission-based commands as needed.

**Comment by FrNico** [comment]
Adding to that thread, a botkeeper should have right for /bot leave
Also with monitoradds plugin, a botkeeper should be granted rights to add users to HO without warning message (seems only admin can today).

**Comment by Riptides** [comment]
@FrNico admins and mods should both be able to add users to HOs currently.
Although I'm now leaning more towards combining the roles of botkeeper and mod.

**Comment by Deuteu** [comment]
Hi!

I've worked on that for @FrNico last night. I've some lines :
https://github.com/Deuteu/hangupsbot/blob/3d89445197335070d4b34183f63d66ce4c440299/hangupsbot/handlers.py
Not perfect yet and moreover not tested.

But it made me thought about this issue #177 Whitelist versus blacklist.

**Comment by FrNico** [comment]
If we recap list of roles, and default commands allowed, I think something like that is a good start:
 - admin: [global] [all]
 - botkeeper: [global config] leave, createconversation, whereami
 - mods: [per conv_id config]: addme, addusers,  leave, invite, refresh, rename, topic, whereami (restricted to conv_id)
 - comm: [global config] broadcast
 - users: dnd, help, mention, optout, rsvp, setnickname, subscribe, unsubscribe

**Comment by Deuteu** [comment]
Need opinion :
Currently admin list is stored in config whereas "botkeeper" (someone who can add bot to a conv with restictedadd plugin) is stored in memory.
What is best to do for roles?
Admin should maybe (like in retrictedadd plugin) have the possibility to assign a role to someone with a command so is it possible to rewrite config (need a reload of the bot?) in a function?

**Comment by endofline** [comment]
Question on multiple roles: I can't be a botkeeper and a mod at the same time?

**Comment by FrNico** [comment]
botkeeper also should be a global_config thing (can't keep anything before creating it!), while mods should be per conversation.

**Comment by endofline** [comment]
Update: In #256, I'm implementing a general tagging system which allows 3 times of tagging: per-user, per-conversation and per-conversation-user-override. The important types of tags for roles is **per-user** which effectively defines a global set of tags for a specific user, and **per-conversation-user-override** tags which will take precedence and overwrite any global **per-user** tag. 

Please give me any feedback on anything to add/consider for the tags implementation. 

I've thought about additive/subtractive tagging, i.e. the ability to combine tags from per-user and per-conversation-user-override (instead of one overriding the other),perhaps by adding the "+" or "-" prefix to a tag to add/remove tags (`-mod`, `+botkeeper`). After some thought, I will reserve this idea for another day as it definitely confuses botmins managing access control.

Note: The **per-conversation** tag is less important for this implementation, and used for other purposes such as for grouping conversations.

**Comment by endofline** [comment]
plugins restrictedadd (f24f1b4) and monitoradd (3821608) have been modified to support tags, in addition to the legacy methods based on the tagging system in #256

**Comment by pleasantone** [comment]
Is this the basic resolution and framework going forward, or are there still thoughts about making something more generic across all plugins?

**Comment by endofline** [comment]
@pleasantone to summarise the above, yes - the tagging implementation in #256 provides an extensible backend for access control. It's up to individual plugin devs to implement their own support for anything more than user/admin-level based access. Feel free to make suggestions/feedback in this thread since there might be missing features.

**Comment by endofline** [comment]
Wiki updated:
* https://github.com/hangoutsbot/hangoutsbot/wiki/Reference:-Tags-List
* https://github.com/hangoutsbot/hangoutsbot/wiki/Reference:-User-and-Conversation-Tagging
* https://github.com/hangoutsbot/hangoutsbot/wiki/Autoreply-Plugin
* https://github.com/hangoutsbot/hangoutsbot/wiki/Restricted-Add-Plugin
* https://github.com/hangoutsbot/hangoutsbot/wiki/Monitoradds-Plugin

**Comment by endofline** [comment]
Please note that #256 has been merged to staging :)

**Comment by endofline** [comment]
Closing this now that #300 has been released - feel free to create more separate issues related to this :)
