### ISSUE TITLE
create 1-to-1 conversation as needed, formerly "Cannot @mention probable workaround"

### ISSUE THREAD

**Issue by 00svbeon** [hangoutsbot/hangoutsbot#202]
When a user you are trying to @menrion doesn't have a 1-to-1 you are, in the group chat prompted:
"@mention didn't work for {}. User must say something to me first."
Why not use convtools and try create one, followed by "if you do not want these messages /bot optout"

**Comment by 00svbeon** [comment]
Or send that in 1-to-1 to the one who @mentioned... It's disturbing in group conversations...

**Comment by nylonee** [comment]
I believe @endofline has already implemented this using convtools to create the conversation if it doesn't exist. I'm not sure how to turn it on though, he could probably guide you through that.

As for the /bot optout message, that's probably a good idea, it could very quickly make users annoyed otherwise.

**Comment by endofline** [comment]
Note that this feature is still experimental due to possible ABUSE_OVERQUOTA errors from the server, it can be manually enabled by the botmins with `config.autocreate-1to1`

Related code here: https://github.com/hangoutsbot/hangoutsbot/blob/4bfef22b501b51cc10d85aa4f234017d15298353/hangupsbot/hangupsbot.py#L391

**Comment by endofline** [comment]
About the mention error, that can be shut off by botmins with `config.mentionerrors`

Wiki entry for this config option here:
https://github.com/hangoutsbot/hangoutsbot/wiki/Mentions-Plugin#admins-configuration

**Comment by 00svbeon** [comment]
Ah that's true, maybe add this to the wiki

**Comment by endofline** [comment]
Leaving this open until `config.autocreate-1to1` becomes permanent

**Comment by endofline** [comment]
Wiki updated: https://github.com/hangoutsbot/hangoutsbot/wiki/Configuration#autocreate1to1

**Comment by endofline** [comment]
Confirmed and added in #300
