### ISSUE TITLE
/bot users [CID] for admins 

### ISSUE THREAD

**Issue by 00svbeon** [hangoutsbot/hangoutsbot#214]
Sometimes iI don't want to spam a 150ppl hour with the users list, but iIend it. Might i, as bmim be able to issue `/bot users [CID]` in my 1-to-1 with the bot to get that list as a pm

**Comment by endofline** [comment]
`/bot syncusers <convid>` can be used as a temporary method to retrieve user lists in other conversations: https://github.com/hangoutsbot/hangoutsbot/wiki/Syncouts-Plugin#commands 

A native default command is on the way, and needs to be integrated with the convmem plugin, which offers more reliable conversation user listings than the internal hangups method (due to the forgotten conversation bug, re: #166)

**Comment by 00svbeon** [comment]
Yeah iI knew that one but I just suggested a standard 😉

**Comment by endofline** [comment]
Adding to the above: docs can be found here: https://github.com/hangoutsbot/hangoutsbot/wiki/Default-Commands-Plugin#convid-family
