### ISSUE TITLE
Unverified HTTPS request is being made.

### ISSUE THREAD

**Issue by mxxcon** [hangoutsbot/hangoutsbot#237]
Bot Version: 2.4.2
`hangupsbot_error.log` is full of these entries
>`  InsecureRequestWarning)`
>`/usr/local/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html`

**Comment by endofline** [comment]
I've observed this during slack plugin operation and it seems to be raised from within the slack library itself - most likely because its doing a POST request with `verify=False`. The warning is expected in such a scenario. 

CC: @nylonee 

The warning can be observed by redirecting `stderror` or running the bot directly from console.

**Comment by endofline** [comment]
This probably related: https://github.com/loisaidasam/pyslack/issues/16

**Comment by endofline** [comment]
This appears to be the reasoning why its not making validated requests: https://github.com/loisaidasam/pyslack/commit/678b95bed45bd3582f4cdb4f5e9ec7ceafc7fcc5

**Comment by mxxcon** [comment]
678b95b is more than a year old. Is that problem still relevant? https://www.ssllabs.com/ssltest/analyze.html?d=api.slack.com&latest shows pretty good results.

**Comment by endofline** [comment]
This would be a pull request that needs to be made of the external library repo. The commit also specifies "intermittent ssl failure", so a single test would probably not be sufficiently diagnostic.

I do agree its probably no longer relevant since its been a year+, but if the repo is no longer active, then somebody will probably have to fork it to merge updates and test it again. This guy made a fork that appears to perform validation: https://github.com/chrisgilbert/pyslack/commit/89eea27bc065c9d5f7ceb28ac89ce67ce9a78796

**Comment by endofline** [comment]
The pyslack ssl verification issue has been resolved with https://github.com/loisaidasam/pyslack/issues/21

**Comment by endofline** [comment]
A fix has been applied, you will also need to upgrade your PySlack library to the latest version since this change is fairly recent:
```
pip3 install git+https://github.com/loisaidasam/pyslack.git --upgrade
```

**Comment by endofline** [comment]
Verified in #331
