### ISSUE TITLE
[support] customising /bot leave statement

### ISSUE THREAD

**Issue by bmbermn** [hangoutsbot/hangoutsbot#287]
Can you direct me to where the "Leave" command is located in the code? I want to add/change it to a custom phrase if possible.

**Comment by endofline** [comment]
[Here ;P](https://github.com/hangoutsbot/hangoutsbot/search?utf8=%E2%9C%93&q=i%27ll+be+back) - you could actually use a [localisation file](https://github.com/hangoutsbot/hangoutsbot-locales/blob/master/en/LC_MESSAGES/hangupsbot.po#L375) to change it actually, as well modifying it manually (although it might get overwritten with newer pulls)

**Comment by bmbermn** [comment]
The localisation file looks like a good option but from what I see its only
outputs, I want to actually change leave to something else "Autobots
RollOut" in my scenario. How would I do that from localization?

**Comment by endofline** [comment]
You can modify your local code as you previously suggested, just make sure that you exercise due diligence if you update your code manually (i.e. download zip files and extract), otherwise new changes to the plugin might override your old code. If you use git pull/merge to update then generally you won't face problems with local changes since git merge is intelligent enough to merge line changes without affecting the entire file.

**Comment by endofline** [comment]
Localisation is an entirely different topic on its own, but basically entails creating your own version of the english messages file I referenced previously (or any other desired language); modifying the labels you want; compiling a binary .mo file out of it; then loading it into the bot as a new locale. Straightforward, but nevertheless somewhat overkill if you only need to change a single label.

More info can be found here: http://stackoverflow.com/a/1079473
