### ISSUE TITLE
[plugin] ERROR_INVALID_CONVERSATION raised when forwarding messages

### ISSUE THREAD

**Issue by bmbermn** [hangoutsbot/hangoutsbot#294]
I attempted to set up forwarding using the example config: 
```
    "CONV_ID1": {
      "forwarding_enabled": true,
      "forward_to": {"CONV_ID2"}
    }
```

So I used the hangouts command to get a list of conversations and came up with 
```
"XXXXXXXXXXXXXXXXXXXXXXXX": {
      "forwarding_enabled": true,
      "forward_to": "XXXXXXXXXXXXXXXXXXXXXXXX"
    }
```

which should forward messages from one group chat to another group chat. However when I do that I get an error any time it tries to sync. 
```
hangups.exceptions.NetworkError: Unexpected status: ERROR_INVALID_CONVERSATION
```

I cannot understand why it is telling me invalid conversation when I got its handle from the hangouts command. 

Can you advise what I am doing wrong?

Thanks 

Edit: For clarity. Removed conversation ids just in case - @endofline

**Comment by bmbermn** [comment]
I just realized I didnt grab the full error message:

17:05:13 ERROR root: FAILED TO SEND MESSAGE
Traceback (most recent call last):
  File "hangoutsbot/hangupsbot/hangupsbot.py", line 608, in _on_message_sent
    future.result()
  File "/usr/local/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
  File "/usr/local/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "hangoutsbot/hangupsbot/hangupsbot.py", line 361, in _begin_message_sending
    yield from _fc.send_message(response[1], image_id=image_id, otr_status=otr_status)
  File "hangoutsbot/hangupsbot/hangupsbot.py", line 69, in send_message
    image_id=image_id, otr_status=otr_status
  File "/usr/local/lib/python3.4/site-packages/hangups/client.py", line 436, in sendchatmessage
    .format(res_status))
hangups.exceptions.NetworkError: Unexpected status: ERROR_INVALID_CONVERSATION

**Comment by endofline** [comment]
Further information required:
* Is the bot actually a member of the conversation specified in `forward_to`? 
  * If yes, what is the output of `/bot whereami` inside that conversation and compare it with the conversation id returned by `/bot hangouts` - any discrepancies?

**Comment by bmbermn** [comment]
Here is the config as the bot spits it out and the copied chat id from the
room I want it forwarded to. They do match.

**Comment by endofline** [comment]
`ERROR_INVALID_CONVERSATION` generally only shows up if the conversation does not exist for the bot - there are a number of possible reasons why this can occur:

1. The conversation id is incorrect - previously some command outputs experienced "markdown mangling" because double underscores (`__`) was erroneously consumed by the message parser
and re-output as a single underscore ('_') in certain edge-cases
  * To verify this is the case, and **assuming that the bot is a member of the conversation** 
     specified in `forward_to`, proceed to that conversation and issue the command `/bot whereami` - 
     if the resulting conversation id doesn't match the output of `/bot hangouts`, do let me know
     so we can patch this in upcoming releases
2. The actual conversation doesn't exist in the bot backend, but somehow exists in bot memory
  * To verify this is the case, then your bot should **not be a member of the conversation** specified
     in the `forward_to`, but the **title still shows up in `/bot hangouts`**. Please inform if this is the
     case.
  * To workaround this problem, add the bot back into that conversation
3. Some other obscure error we never encountered before
  * If this is the case, then further investigation is warranted.

Also, in any of these situations, please also specify the output of `/bot version` so we know which version of the bot you are running.

**Comment by endofline** [comment]
This might be the issue:

First, the documentation is incorrect:
```json
 "forward_to": { "CONV_ID2" }
```
should be:
```json
"forward_to": [ "CONV_ID2" ]
```

This has been updated in the wiki (cc: @nylonee)

Secondly, in your configuration:
```json
 "forward_to": "XXXXXXXXXXXXXXXXXXXXXXXX"
```
should be:
```json
"forward_to": [ "XXXXXXXXXXXXXXXXXXXXXXXX" ]
```

The conversation id must be enclosed as a list, as this allows forwarding to multiple conversations instead of just 1 at a time. By not enclosing it as a list, the plugin will interpret the string as a list and try and forward the message to each letter in the conversation id one-by-one.

**Comment by bmbermn** [comment]
Awesome! Thats exactly what the issue was. Thanks for your help.

On Sat, Aug 1, 2015 at 9:53 PM, Innocent Bystander <notifications@github.com

**Comment by endofline** [comment]
Closing this issue since its apparently resolved
