### ISSUE TITLE
Cleverbot percentage replies not functioning

### ISSUE THREAD

**Issue by Raptor123471** [hangoutsbot/hangoutsbot#352]
I am using the latest master branch, and have also tried the latest staging branch with no success. My reply percentage is set to 100 and there is no response from the bot in either my group chat or through PM. There are no errors or indication the plugin is not working, and the /bot chat command is working normally. I did a complete reinstall of Ubuntu and hangupsbot with the same problem.

**Comment by endofline** [comment]
You can try staging again, bfa393ea71f9f3ea7043b2c06388638cec8e03bc fixes the percentage problem due to a change in system architecture. However the cleverbot.com site seems a bit finicky today and apparently changed its own API as well - so you may get weird behaviour such as no replies from the bot. You can try reset the API for a given connection with `/bot chatreset` - which essentially simulates a new a fresh new connection to the cleverbot.com site.
