### ISSUE TITLE
/bot help <command> is case sensitive

### ISSUE THREAD

**Issue by pleasantone** [hangoutsbot/hangoutsbot#353]
/bot command is now case insensitive (yay for phone users!!!)

/bot help command is not

/bot Whereami works
/bot help Whereami fails

How do you feel about making command.commands[] a CaseInsensitiveDict given that we import requests anyway?

The potential fix is (in commands/__init__.py):

from requests.structures import CaseInsensitiveDict

and change self.commands = {} to self.commands = CaseInsensitiveDict({})

We could get rid of the lowercasing as well then...

It looks like you're concerned of backwards incompatibility, I'm less so, personally, but I get it.
I just started using it in my plugins and love CaseInsensitiveDict. I wish it were part of base python.

If you just want to do help, something like this might work (untested as I'm running out the door):
```
    else:
        try:
            command_fn = command.commands.get(cmd) or command.commands[cmd.lower()]
            help_lines.append("<b>{}</b>: {}".format(cmd, command_fn.__doc__))
        except KeyError:
            yield from command.unknown_command(bot, event)
            return
```

**Comment by endofline** [comment]
I took the "naive" path instead of checking the command case, rather than implementing 'requests.structures.CaseInsensitiveDict' for `/bot help` (you can use that as you wish in plugins though, I will make similar considerations in the future!). Reason being that `command.commands` is in use everywhere by framework and plugins and will require a lot more testing, even if its supposed to _just work_ - in any event the naive implementation has the same effect, and as a bonus returns the original case of the command name.
