### ISSUE TITLE
Slack should not require multiple sinks per slack-team.

### ISSUE THREAD

**Issue by pleasantone** [hangoutsbot/hangoutsbot#373]
1. The slack plugin should not need to open up a port per channel as an incoming sink. In fact, it doesn't even need to open one per team. We just need a single port for everything.
2. The slack plugin currently does not check Slack's authenticator coming back into HO to see if this is a valid slack outgoing webhook.
3. Support multiple ports and the old configuration syntax for backwards compatibility.

```
"slack": [
    {
    "certfile": "/etc/ssl/private/example.pem",
    "name": "example.org",
    "port": 9001,
    "teams": {
        "bigcity": {
        "slack_api_key": "xoxb-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "conversation_map": [
            {
            "channel": "financial-district",
            "authenticator": "<slack authenticator for response>",
            "hangouts": [ "UgyXXXXXXXXXXXXABAQ", "UgyXXXXXXXXXXXXABAQ" ]
            },
            {
            "channel": "eastern-wasteland",
            "authenticator": "<slack authenticator for response>",
            "hangouts": [ "UgyXXXXXXXXXXXXABAQ" ]
            }
        ]
        },
        "bigworld": {
        "slack_api_key": "xoxb-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        "conversation_map": [
            {
            "channel": "whatever",
            "authenticator": "<slack authenticator for response>",
            "hangouts": [ "UgyXXXXXXXXXXXXABAQ", "UgyXXXXXXXXXXXXABAQ" ]
            },
            {
            "channel": "eastern-wasteland",
            "authenticator": "<slack authenticator for response>",
            "hangouts": [ "UgyXXXXXXXXXXXXABAQ" ]
            }
        ]
        }
        }
    },
    {
    "certfile": "/etc/ssl/private/example.pem",
    "name": "example.org",
    "port": 9002,
    "..."
    }
]
```

@endofline please share your thoughts

**Comment by pleasantone** [comment]
Gah, cut and past perfectly good json and it's still a mess.

**Comment by endofline** [comment]
Are the teams required just to match the API keys and authenticator? Or are they required for other differentiation purposes. As demonstrated by the copy/paste, if we could reduce the depth of the config  to ease configuration.

**Comment by pleasantone** [comment]
Teams not needed, slack uses api key to select team. Authenticator is a security issue to stop people from spoofing slack

**Comment by nylonee** [comment]
I was just about to note that slack does not require multiple sinks, you beat me to it!
The proposed json above looks good, we can even reduce the teams to an array if we're okay with sacrificing readability a little:
```
"teams": [
      {
            "slack_api_key": "xoxb-XXXXXXXXXXXXXXXX",
              ...
      },
      {
            "slack_api_key": "xoxb-XXXXXXXXXXXXXXXX",
            ...
      }
]
```

**Comment by nylonee** [comment]
If we made the authenticator field optional, I'm assuming we can do a complete migration from the old config to the new, so that we won't have to worry about backward compatibility.

**Comment by pleasantone** [comment]
Yes

**Comment by endofline** [comment]
Since slack teams are unique to slack and we are attempting some standardisation (re: #232), would this be a suitable config then?

Notes:
* `slack.teams` separated from main body
* `conversation_map` at "root" of slack sink config
* More of a caveat: the new slack key can optionally no longer be wrapped in a list, since its a single unified configuration (but I left it in anyway, since its based on previous example)

```json
"slack": [
{
  "certfile": "/etc/ssl/private/example.pem",
  "name": "example.org",
  "port": 9001,
  "slack.teams": {
    "a-team": { 
      "slack_api_key": "xoxb-XXXXXXXXXXXXXXXX",
    },
    "b-team": { 
      "slack_api_key": "xoxb-XXXXXXXXXXXXXXXX",
    }
  },
  "conversation_map": [
    {
      "external": ["#financial-district"],
      "authenticator": "<slack authenticator for response>",
      "hangouts": [ "UgyXXXXXXXXXXXXABAQ", "UgyXXXXXXXXXXXXABAQ" ]
    },
    {
      "external": ["#eastern-wasteland"],
      "authenticator": "<slack authenticator for response>",
      "hangouts": [ "UgyXXXXXXXXXXXXABAQ", "UgyXXXXXXXXXXXXABAQ" ]
    }
  ]
}
]
```

**Comment by pleasantone** [comment]
Makes no sense, doesn't map key to team, but I can change maps back to an array. I just used the team name as documentation, and because I hate keyless dicts

**Comment by pleasantone** [comment]
@nylonee We can totally make the authenticator field optional, it's just protecting against false injections.

@endofline I'm happy to rearrange, but I'm not seeing something really logical. The team name as key in the dict was totally just for documentation, but is not used anywhere.  In order for us to send a message to slack, we need:
1 api key (team specific) [required]
2. channel name (team specific) [required]

In order to receive a message from Slack, we need to provide, to it:
1. Hangout ID
2. IP address/port of receiver
3. Ability to check against a Slack authenticator token (team AND channel specific) (optional)

So, when I'm receiving something, the lookup I need to do is look through all maps that contain hangout ID, and look for the auth token, if it exists.  Ideally, I'd key off of the hangout-id, but understand that it is possible for multiple slacks to send to a single hangout (unusual but possible).

When I'm transmitting something, the lookup I need to do is look at all outbound slack bridges, again, keyed off of the hangout ID that the message is coming from.

So, I could imagine this as the least possibly nested way of doing things, but it violates your rather reasonable request for standardization, but that said, this really _is_ what the data wants... more or less.
I'm not super happy with it,, because it's far from self-documenting, but I tried to make it "make sense".
```
"slack": [
    {
	"certfile": "/etc/ssl/private/example.pem",
	"name": "example.org",
	"port": 9001,

	"UgyXXXXXXXXXXXXXXXABAQ": [
	    "xoxb-xxxxxxxxxxxxxxx": [
		[ "#foobar", "optional-authenticator-for-webhook" ]
		[ "#channel2" ]
	    ],
	    "xoxb-yyyyyyyyyyyyyyy": [
		[ "#baz1" ]
		[ "#channel4" ]
	    ]
        ],
	"UgyZZZZZZZZZZZZZZZABAQ": [
	    "xoxb-xxxxxxxxxxxxxxx": [
		[ "#zombies", "optional-authenticator-for-webhook" ]
		[ "#network23" ]
	    ],
	    "xoxb-yyyyyyyyyyyyyyy": [
		[ "#baz2" ]
		[ "#bbcradio4" ]
	    ]
        ]
    }
]
```

If we can decide on the config structure, I can write the code easily enough.

**Comment by endofline** [comment]
Personally, I would go for standardisation in the `config.json` part. On the other hand, the internal representation may well resemble your above data structure, which obviously makes more logical sense if you are trying to adapt the aiohttp.web routes in the listener class. I have no objections on internal representation whatsoever. At this point, I will request that the config structure resemble the following snippet:
```json
  "conversation_map": [
    {
      "externals": ["#zombies", "#baz2"],
      "hangouts": [ "UgyZZZZZZZZZZZZZZZABAQ", "UgyZZZZZZZZZZZZZZZABAQ" ]
    }
  ]
```

The pertinent points (just to repeat) are:
* have a key called `conversation_map`, so that all plugins of similar design have this
* the internal structure must allow for a list-based `externals` and `hangouts` key (note the `s`)
  * for flexibility, you may optionally specify an atomic string in place of a list, but the atomic string should be internally converted into a single item list
* extra configuration keys may be added into the `conversation_map` if so required, or one level up in the primary configuration depending on the scope (i.e. certfile, ip, etc)

Then, we can override the `__init__` method in the listener class and convert the configuration into the logical lookup form you are proposing - a "refresh from config" method is optional, since we can dynamically reload plugins (and their config) anyway

The reason why this standardised form is required is to resolve future issues with externals synchronisation. It's most likely we have to develop a "relay coordinator" plugin that can determine which messages should be relayed to which externals/hangouts - it should function as transparently as possible and "just work" so to speak if a user attempts decide to create an omnibus hangouts that syncs with slack, telegram, another hangout and maybe whatsapp all at once.

P.S. Your logical design unnerves me @pleasantone, but that's probably because it resembles Google's protobuf, which - although fairly straightforward to parse with the correct libraries - is a particular nightmare to parse by "hand" when doing eye-ball reverse-engineering :stuck_out_tongue:

**Comment by pleasantone** [comment]
OK, I'm going to go with your structure proposal from 21 hours ago.  It's the most readable, collapses nesting, and hopefully will be in line with your future vision.

```
"slack": [
  {
    "certfile": "/etc/ssl/private/example.pem",
    "name": "example.org",
    "port": 9001,

    "team_map": {
        "team-a": { "api_key" : "xoxb-xxxxxxxxxxxxxxxxxxxxxx" },
        "team-b": { "api_key" : "xoxb-yyyyyyyyyyyyyyyyyyyyyy" }
    },
    "conversation_map": [
      {
        "team": "team-a",
        "hangouts": [ "UgyXXXXXXXXXXXXXXXABAQ", "UgyZZZZZZZZZZZZZZZABAQ" ],
        "externals": ["#zombies", "#second_channel" ],
        "inbound_authenticators": [ "kjdlhsdiluhweiuhwe", "second channel auth" ]
      },
      {
        "team": "team-b",
        "externals": ["#plants"],
        "hangouts": [ "UgyZZZZZZZZZZZZZZZABAQ" ]
      }
    ]
  }
]
```

**Comment by pleasantone** [comment]
per-our-discussion - rev 0 -- doesn't even compile, but basic structure
https://gist.github.com/pleasantone/07d5d707d000c166e4cd

That said, maybe it's time to discuss/refactor the _handle_websync code now, to make it more friendly to your new design now. We're both overriding that routine, @endofline

**Comment by pleasantone** [comment]
The SlackRTM plugin handles this issue better than ours. Close this when it gets imported.
