### ISSUE TITLE
Question on Plugins

### ISSUE THREAD

**Issue by bmbermn** [hangoutsbot/hangoutsbot#374]
I would like to create a plugin (preferably in a custom directory so it does not get autoloaded with null) that I can specify on a per conversation basis. Is that possible? I cant find how to do it.

**Comment by endofline** [comment]
You can't load a plugin on a per-conversation basis. You can simulate it though, since every command and handler receives an `event` object. The `event` object contains a `conv_id` which you can compare against a preset list of conversation ids and determine whether to run the command/handler or not

**Comment by endofline** [comment]
Additionally, if its just simple commands, you can grant/remove access to commands via [Access Control with Tags](https://github.com/hangoutsbot/hangoutsbot/wiki/Access-Control-with-Tags)
