### ISSUE TITLE
Forecast plugin:  /bot forecast should be /bot weather

### ISSUE THREAD

**Issue by cntrlwiz** [hangoutsbot/hangoutsbot#499]
In both master and staging branches:
1. The command /bot forecast provides the current weather, not a forecast.
2. The error message when there is no saved location states "Your location history not found. Use /bot weather address", also implying that command should be "weather", not "forecast".

**Comment by cntrlwiz** [comment]
Thanks, vigoren!  You fixed the issue and read my mind concerning my next request for the forecast plugin.

**Comment by pleasantone** [comment]
I called it forecast because it uses forecast.io and weather seemed too generic and likely to conflict with other future plugins.

**Comment by cntrlwiz** [comment]
It's appropriate to call the plug in "forecast".
But, to call a command that responds with current weather "forecast" instead of something like "weather", "conditions", etc. just confuses the users who don't know or care where the data comes from.
Honestly, it seemed like a typo, and no slight intended.

**Comment by JosephBlock** [comment]
keep it /bot forecast, but add a option request week forecast.   As I see it a single day is still a forecast...

**Comment by cntrlwiz** [comment]
The current weather conditions are not a forecast.

**Comment by thannemann** [comment]
But its related to the forecast.io website. However I dint see most people running more than one weather plugin so I dint think it would 've an issue

**Comment by cntrlwiz** [comment]
Which is why I said that it's appropriate to name the plug in "forecast".  But the users that don't know that are confused.

**Comment by vigoren** [comment]
the /bot weather command pulls the current weather information from forecast.io which is why I called it weather. 
the /bot forecast command pulls the forecast for the next 24 hours and 7 days.

If using weather is a concern we could change it to /bot currentweather but that seems like adding words for the sake of adding words. I also agree that most bots will probably only run one weather plugin or if more weather plugins are created, perhaps pulling from different sources, they could all be lumped into this one and by setting a configuration option determine which service you are using.

**Comment by nylonee** [comment]
This has been merged in #500
