### ISSUE TITLE
Make bot admin commands more intuitive

### ISSUE THREAD

**Issue by pleasantone** [hangoutsbot/hangoutsbot#522]
The bot commands are a cruel hazing ritual for new admins. We need to clean them up to make them more intuitive.

/bot convfilter comes to mind

**Comment by gurumadmat** [comment]
Convid commands were made by @endofline for others to build plugins around. Making simple useful admin commands.  No one does though.

**Comment by nylonee** [comment]
A plugin that maps the powerful convtools to easier commands comes to mind, however in order to do this I'd really like to see a distinction between an admin and a bot sysadmin. See #381 

Otherwise typing /bot help would still give you a wall of commands that you'd probably never need and confuse admins to no end.
