### ISSUE TITLE
[feature request] Option to disable '/bot' requirement for command

### ISSUE THREAD

**Issue by triune** [hangoutsbot/hangoutsbot#532]
Allow bot to respond to all msgs without a command alias.

/bot help
...becomes...
help

/bot version
...becomes...
version

Maybe a secret \\\\ can turn this on?

  "bot.command_aliases": [
    "\\\\"
  ],

**Comment by triune** [comment]
..of course
"silentmode": true,
would have to be on to use this feature :)

**Comment by gurumadmat** [comment]
There is already a PR ( #508 ) that does this in 1-0N -1.

For group conversations I don't think this is useful.

**Comment by triune** [comment]
@gurumadmat that looks like a really simple patch #508 ... why not allow this for someone that does think this would be a useful feature?

I'm in several HO's where I can imagine that having the bot interact naturally to commands like 
forecast
catfact
wiki
urbandict
etc...
would be very useful to have. Also, when using HO on mobile, this would make it a lot easier to interact with the bot ~ less keypad typing / no prefix.

**Comment by gurumadmat** [comment]
@triune
I'm not keeping you from taking the code in #508 and adjusting it to work
on all conversations.

It is always allowed to make adjustments for yourself.
But in my opinion this will be counterproductive and I won't spend time on
it.

**Comment by triune** [comment]
@gurumadmat if I got it to work would you accept a pull request to add it in?

**Comment by nylonee** [comment]
@triune Feel free to make a PR, I imagine this is a feature that several people would like. If there are any issues with the PR then discussion will happen before the PR gets merged. Some things to watch out for:
- Make sure the code is backward compatible
- Make it an option instead of forcing all current bot instances to switch to the new system
- The wiki should be well documented with the changes you've made (to happen after you've made a PR)

**Comment by triune** [comment]
@nylonee I made a patch and the pull request is here: https://github.com/hangoutsbot/hangoutsbot/pull/545

**Comment by endofline** [comment]
this feature request appears to have gone stale
