### ISSUE TITLE
Using a current version of hangups

### ISSUE THREAD

**Issue by redkite** [hangoutsbot/hangoutsbot#560]
The version of hangups used for hangoutsbot has diverged quite a bit from the original hangups repository. Is there any chance the version requirement for hangups will be pushed upwards to a recent version?

There some changes like the order of messages being sent (https://github.com/tdryer/hangups/issues/75) that would be more than only nice to have. Is there any reason for this not happening?

**Comment by thannemann** [comment]
It is a huge undertaking and we don't have the resources to do this easily and quickly.  there is a lot of items within the hangoutbot that is dependent on the current version and breaks with the new version of hagups, which is why we have our own version, of the old code and continue to patch it as it breaks.

**Comment by redkite** [comment]
Is there a realistic chance that message ordering from slack to hangouts will be fixed in the own legacy version of hangups? I would file a new bug then.

**Comment by pleasantone** [comment]
@redkite Please file a new issue with that one particular issue, and reference this but (#560) in it.

**Comment by endofline** [comment]
currently being done in https://github.com/hangoutsbot/hangoutsbot/tree/v3.0

**Comment by Terrance** [comment]
v3 is now released and uses the current upstream version of hangups.
