### ISSUE TITLE
telesync plugin incompatible with current version of telepot

### ISSUE THREAD

**Issue by fizux** [hangoutsbot/hangoutsbot#583]
requirements.txt specifies telepot >= 6.5; however, as of telepot 7.0+ (current = 8.0) the method "messageLoop" has become "message_loop" and breaks the plugin at plugins/telesync/__init__.py , line 501.

**Comment by 1110101** [comment]
This will be fixed #562

**Comment by makiftasova** [comment]
some other bad news regarding the telepot library. recently telepot library was upgraded to v8.x thus breaking asyncio compatibility with python3.4 (it requires python3.5+ because 3.4 doesn't support await keyword.)

in this case either we will stick with an older version of telepot and get no further updates, or switch to telepot 8.x line but drop compatibility with python3.4
