### ISSUE TITLE
Deprecate plugins that can be replaced by spawns

### ISSUE THREAD

**Issue by pleasantone** [hangoutsbot/hangoutsbot#685]
The following plugins are candidates for removal/replacement from hangoutsbot/plugins:

These plugins could be standalone programs that use the spawn interface. There is no need to maintain them as part of the core plugins, they simply respond with text information and make no use of hangouts internals, no do they upload images (which would require a sink).  In addition,
most of them hang the entire bot while executing (sometimes waiting for information from a remote site to be returned).

- [ ] cleverbot
- [ ] catfact
- [ ] forecast
- [ ] foursquare
- [ ] lookup
- [ ] lottery
- [ ] metar
- [ ] simplewikipedia
- [ ] tldr
- [ ] urbandict
- [ ] wolframalpha

These plugins could be replaced with standalone programs that write to sinks. They wait for external events and just dump text notifications to a hangout:

- [ ] spotify
- [ ] twitter

**Comment by jimsug** [comment]
Hmm - I'll try to take a look at some of these. Not sure if there's a sink that will handle what the twitter plugin does out of the box (it actually listens for _chat_ messages and writes to the hangout, rather than external events **and it also uploads images if present in the tweet**) but happy to have a go at it.

The remainder of the plugins - just from a cursory overview - look like they could be made standalone.

From a repo management POV - would we prefer to have them referenced/included in this project, or perhaps just mentioned in a directory page of the wiki?

**Comment by pleasantone** [comment]
Jim, thanks, it's a good question how we want to distribute spawns. I think a wiki entry is reasonable, and if something is really bot specific, we can start a spawns subproject. I don't expect us to kill off all these plugins, but I would like to prescriptively have examples of good spawns.

Maybe we should take a crack at a few of the examples, and use those to game the infrastructure?

Nice catch on twitter!

**Comment by jimsug** [comment]
Oh, the other thing is - and I haven't looked at the spawn plugin properly, but - it doesn't look like there's a good way to specify help text unless authors always set `allow_args` to `true` (or we make a special exception).

**Comment by pleasantone** [comment]
Help text could become yet another field in the config?

**Comment by GNUGradyn** [comment]
Memes can also be replaced with spawns
