### ISSUE TITLE
refactor pluginmanager into plugin control commands

### ISSUE THREAD

**Issue by endofline** [hangoutsbot/hangoutsbot#752]
The plugin manager plugin adds unnecessary clutter to the plugins folder and also contains functionality that should be subsumed into the framework-level plugin control commands. Confusingly there are two wiki entries for these as well:
* https://github.com/hangoutsbot/hangoutsbot/wiki/Plugin-Control-Commands
* https://github.com/hangoutsbot/hangoutsbot/wiki/Pluginmanager-Plugin

**Comment by endofline** [comment]
although this is blocking 3.0, changes can be made to either staging/v2 **or** to the v3 branch

**Comment by nylonee** [comment]
Will absorb the functionality from pluginmanager into the framework-level plugin control commands.

Note that the plugin was developed for non-technical admins, specifically since it allowed easy toggling of commands without knowing the submodule that it's in (eg. `/bot pluginload plugins.restrictedadd` vs `/bot addplugin restrictedadd`)

**Comment by endofline** [comment]
i can see the need for it. nevertheless, functionality can be implemented without compromising accessibility or useability, and this was actually raised in a much earlier issue: https://github.com/hangoutsbot/hangoutsbot/issues/122#issuecomment-131670349
