### ISSUE TITLE
Delay sending messages (HTTP API)

### ISSUE THREAD

**Issue by KoalaBear84** [hangoutsbot/hangoutsbot#757]
I couldn't find the problem myself. Sometimes we send 3 messages in a row to the HTTP API. Between every message there is a big delay of 2-10 seconds.

Can anyone tell me how or why. And is this solveable? Thanks!

Here is some example C# code to test the issue. It will call the HTTP API 3 times.
```csharp
public class HangoutsBotBody
{
	[JsonProperty(PropertyName = "key")]
	public string Key { get; set; }

	[JsonProperty(PropertyName = "sendto")]
	public string SendTo { get; set; }

	[JsonProperty(PropertyName = "content")]
	public string Content { get; set; }
}

public async SendMessage(string conversationId, string message)
{
	HttpClient httpClient = new HttpClient();

	HangoutsBotBody hangoutsBotBody = new HangoutsBotBody
	{
		Key = "API-KEY",
		SendTo = conversationId,
		Content = message
	};

	string json = JsonConvert.SerializeObject(hangoutsBotBody);

	StringContent stringContent = new StringContent(json, Encoding.UTF8, "application/json");

	HttpResponseMessage httpResponseMessage = await HttpClient.PostAsync("HangoutsBot URL", stringContent);
}

public void Test()
{
	SendMessage("conversationId", "Message 1");
	SendMessage("conversationId", "Message 2");
	SendMessage("conversationId", "Message 3");
}
```

**Comment by endofline** [comment]
Ah I see, wrong repo ;P I'll close this for you.

**Comment by KoalaBear84** [comment]
No, this is the RIGHT repository. As Hangups itself is just the library.

**Comment by endofline** [comment]
I was momentarily confused by the referenced issue, let me reopen this and look at it for a moment.

**Comment by endofline** [comment]
Pardon my ignorance, but are you sure you have the right repo? Your code resembles .NET code and this repository is almost entirely Python 3. We do use the SendMessage method from the Hangups library, but are not experiencing any issues and the architecture would be entirely different anyway.

**Comment by KoalaBear84** [comment]
I'm sorry for the confusing part. The code is to 'test' the delay. It is not code from hangoutsbot, but example code to call the HTTP API 3 times in a row.

We run Hangoutsbot as is, and call HTTP API to send a message.

Config.json part:
  "plugins": [
    "api"
  ]

**Comment by endofline** [comment]
I just tested this with the [tests/api-send.py](https://github.com/hangoutsbot/hangoutsbot/blob/master/hangupsbot/tests/api-send.py) and there is a noticeable lag for the script to return, but I note that the message itself arrives more or less instantaneously (<0.5 seconds). The pause might be the result of the script waiting for the connection to close due to the ["return response" feature](https://github.com/hangoutsbot/hangoutsbot/blob/master/hangupsbot/plugins/api.py#L159) of the API, which allows a given command to actually send its output back through the http call as a response.  As you can see from the code, it will time out in 3 seconds if no response is available from whatever remote call is made.

Unfortunately, one of the features that made this work - the "reprocessor") - was broken an indeterminate time ago when Google patched their protocol to disallow hidden links, which is used to pass metadata so the bot can identify the message source. So the delay you are experiencing is probably due to the 3 second time-out.

Test and temporary workaround:
* You can manually [reduce the time-out](https://github.com/hangoutsbot/hangoutsbot/blob/master/hangupsbot/plugins/api.py#L160) and see whether this makes it any more responsive. If the output doesn't matter, you can patch it temporarily by reducing/eliminating the timeout.

Long-term fixes:
* The [V3](https://github.com/hangoutsbot/hangoutsbot/tree/v3.0) branch of the bot restores the reprocessor capability by using the Hangouts protocol `Annotation` entity to send the hidden metadata. The code quality at this point for this branch is considered beta. Actual release date has not been determined yet.
* On your .NET side, you can make asynchronous calls to the bot API so that they don't have to wait for the server to return.

**Comment by endofline** [comment]
Are you just using the API to send messages? [Sinks](https://github.com/hangoutsbot/hangoutsbot/wiki/Sinks-(2.4-and-above)) do not wait for response and will suffice if you are only sending messages, as I'm quite sure API calls are broken right now on V2 - they will output to the target conversation/user, but the commands will not execute due to the broken reprocessor. Otherwise you can consider switching to the [v3.0](https://github.com/hangoutsbot/hangoutsbot/tree/v3.0) branch - I've verified that the API plugin is working on this version.

**Comment by KoalaBear84** [comment]
Thanks for your answer! It looks like that the 'waiting on the result' part is part of the problem indeed. If I now do even 5 messages async, it looks like there is no issue.

I will now try to rewrite the sending part and see if it works. If succesfull I will close this issue in the evening.

**Comment by KoalaBear84** [comment]
Thanks again for the very helpful respones about reduce timeout and V3 branch!

We have found some other delays which we fixed, and make it fully async. It's good now!
