### ISSUE TITLE
[v3] Commands issued in Slack to hangoutsbot not processed/responding

### ISSUE THREAD

**Issue by phantomdarkness** [hangoutsbot/hangoutsbot#796]
Bot no longer processes commands sent via Slack to Hangout.  Worked in V2 based on https://github.com/hangoutsbot/hangoutsbot/pull/577

**Comment by endofline** [comment]
SlackRTM is being refactored presently (and will take a day or two) It's
the last remaining plugin (aside from the pending Discord chat) in the
development branch that isn't chatbridge ready. Current development tree:
https://github.com/hangoutsbot/hangoutsbot/tree/chatbridge/telesync
(subject to change)

**Comment by phantomdarkness** [comment]
I figured with all the changes, but just wanted to make sure devs were aware that this broke.

**Comment by pleasantone** [comment]
I don't think it should.

**Comment by endofline** [comment]
I would appreciate knowing your current setup (which platform to which
platform), what you actually did and which branch you are running on. And
if you have the time to test
https://github.com/hangoutsbot/hangoutsbot/tree/chatbridge/telesync which
has the most cutting edge changes in the chatbridge family of plugins +
chatbridge compatible telesync.

Unfortunately chatbridge-compatible slackrtm isn't here yet due to two
years of technical debt it has accumulated ;p If you are testing the branch
I recommend a clean checkout, and not a merge. Existing config should work
with no changes.

The refactoring strategy will be as follows:
1. Modernise internal architecture (slackrtm uses threads!)
2. Make chatbridge compatible (so it won't matter where and how it's used
with other hangouts) - in particular, ensure all bot messages get through
the bridge
3. Work on additional messaging related quirks
4. Work on additional non-messaging quirks

**Comment by phantomdarkness** [comment]
I'm running das7pad's forked version of telesync (https://github.com/hangoutsbot/hangoutsbot/pull/795), but i know others running stock V3 telesync and slackrtm have said that it's not working.

It's not a huge deal if it's something you're working on, can wait till your done.

**Comment by das7pad** [comment]
@phantomdarkness I removed the code for handling the slack message as a bot-command, beause it is a big security issue. As the slack-profile-sync is not merged atm, there is no other user than the bot user to blame for all commands.
With the profile sync, commands can be issued as the synced HO-user. See telesync:
https://github.com/das7pad/hangoutsbot/blob/telesync-das7pad-v3/hangupsbot/plugins/telesync/telegrambot.py#L956..L964
https://github.com/das7pad/hangoutsbot/blob/telesync-das7pad-v3/hangupsbot/plugins/telesync/telegrambot.py#L996..L997

For the API-plugin users might setup the botuser as an admin. Every slackuser would be able to change the config of the bot.
Or think about plugins that restrict access to infos based on conversation-membership - the bot is in every conversation he has infos for.

**Comment by phantomdarkness** [comment]
Ah, didn't realize that can run commands through TG, that's very cool/impressive.  I'll just wait on slackrtm support again, just enjoyed that ability and it's important for a lot of folks.
