### ISSUE TITLE
[telesync] gif not synced

### ISSUE THREAD

**Issue by phantomdarkness** [hangoutsbot/hangoutsbot#801]
GIF images do not sync from TG.  Not related to version (doesn't work in either V2 or V3).  No message in log.

**Comment by JosephBlock** [comment]
GIFs never transferred. I do have a fix for it, but with the current changes of the code I have not submitted a pull request yet.

**Comment by endofline** [comment]
telegram servers convert animated gifs to mp4 according to this [article](https://telegram.org/blog/gif-revolution) - since we need to rely on the image being an actual gif/jpg/png on hangouts, it's unlikely that this feature will be fully implemented (unless somebody wants to put in a possibly heavy h.264 to gif converter somewhere in the plugin, or rely on a third-party site/service to do so)

**Comment by endofline** [comment]
i've added optional gifs.com conversion of telegram-style "animated gifs" (actually mp4) back into actual .gif format for relays. this feature must be explicitly enabled with the following configuration key to telesync:
```
"convert-with-gifscom": <boolean|optional gifs.com api key>
``` 
note: setting key to `true` will use the demo api key, which actually isn't needed. if this key is set to `false` or not defined, telesync will send the static thumbnail of the animated gif instead, as before.

i'll be happy to entertain new PRs that implement offline methods for this, but this will serve as a workaround for now.
