### ISSUE TITLE
improve UX by interpreting conversation IDs and user IDs...

### ISSUE THREAD

**Issue by pleasantone** [hangoutsbot/hangoutsbot#832]
This is a general UI enhancement idea applicable across the entire bot + plugin space.  Originally I was thinking this should be improvements to convtools in a fashion similar to #827 but I really think this should be core to the bot experience and we should simply "fix" the existing code to always respond to this standard instead of doing it piecemeal.

There are a lot of places where we are requiring the users or bot admins to specify a conversation ID (e.g. `UgwVk3ytehRTIoEH_3N4AaABAQ`) or user id (e.g. `108909027823068494460`).  We originally did this because (a) they are unambiguous and (b) anything other than these actual identifiers may change over time.

While I certainly agree that we should do all of our work and store them as IDs, we really need a better UI than we have currently.  For example, if I want to add a user to a group, I need to do something like:

```
    /bot convfilter text:some-bit-of-text-in-the-title
    /bot user <some part of display name>
```

then I scan the list of groups convfilter and users, and finally cut and paste to do:
```
    /bot adduser <user-ids> <chat-id>
```

All I ever really wanted to type was:

```
   /bot adduser Patti into Bluegrass
```

Now, this is "potentially dangerous" so we do need to be sane in the case of ambiguity, but it's fairly easy to determine if we've got ambiguous results and simply raise an exception that brings us back to the command processor again with an error message.

1) Hangout titles substrings need to be unambiguous at the time of their entry and are immediately converted into conversation IDs.

2) Display names need to be unambiguous at the time of their entry and are immediately converted into display names.

I'm also going to throw in here a separate but related idea for "commented" configuration files with regards to any dict like entries involving user IDs or conversation IDs.  We should do "reverse resolution" at the time we translate from name->ID and stuff a comment entry in the dictionary (or, alternatively, reverse resolve it at the time of config.json write, but that's more complicated).

e.g.

```
 "conversations": {
    "UgwVk3ytehRTIoEH_3N4AaABAQ": {
      "calendar": "primary",
      "timezone": "America/Los_Angeles"
    },
    "UgwuLgOtCJcDfOmuxRF4AaABAQ": {
      "mentionall": true
    },
```

get output to config.json as:

```
 "conversations": {
    "UgwVk3ytehRTIoEH_3N4AaABAQ": {
      "x-comment": "Smash and Grab Party",
      "calendar": "primary",
      "timezone": "America/Los_Angeles"
    },
    "UgwuLgOtCJcDfOmuxRF4AaABAQ": {
      "x-comment": "Jimbo's Pickles and Saloon",
      "mentionall": true
    },
```

**Comment by pleasantone** [comment]
Ditto the UX for telegram IDs, telegram users, slack teams, channels, and users...

**Comment by endofline** [comment]
i will experiment with this at the [handle_command](https://github.com/hangoutsbot/hangoutsbot/blob/v3.0/hangupsbot/handlers.py#L231) level - the implementation may have these "traits"/caveats:
* will be transparent for all command handling
* will require some sort of token recognition e.g. "@" for user name fragments and "#" for conversation title fragments i.e. `/bot adduser @johnleong into #part_of_hangouts_title`
* (as per previous example) requires spaces to be excluded or replaced with underscores (otherwise the tokeniser won't know when to stop matching
* will probably follow the matching convention of the `mentions` plugin
* completely new users to the bot will still have to be added to the bot by `chat_id` ,or they must first initiate a two-way dialog with the bot to be recognised by the transparent referencing

other devs are welcome to try alternate implementations in the mean-time.

**Comment by OllieTerrance** [comment]
> will require some sort of token recognition e.g. "@" for user name fragments and "#" for conversation title fragments

That should also come with suitable escaping in case you want a literal `@` or `#` in your command.

> requires spaces to be excluded or replaced with underscores (otherwise the tokeniser won't know when to stop matching

Or multiple words in quotes?  Looks like you're using `shlex.split()` [here](https://github.com/hangoutsbot/hangoutsbot/blob/v3.0/hangupsbot/handlers.py#L259), not sure if that's relevant and/or what other magic goes on though...

---

Alternative implementation idea, just provide documented helper methods e.g.:

* `bot.resolve_conv(conv_name)` -- given a conv ID or unique name fragment, produce a conversation
* `bot.resolve_user(user_name, conv=None)` -- given a user ID or unique name fragment, along with optional conversation to filter on, produce a user
* maybe additional methods to return all matches (if useful, can't think of a good use case for it)

...but then it's up to plugins to make use of them.

**Comment by endofline** [comment]
* literal usage will be problematic with always-on preprocessing and the lack of a customisable parser - the point is well-taken and i'm considering alternatives to the "always-on" strategy
* `shlex` is manageable, some experimental formats like `"user:nick goh"` (works); `user:"po ni"` (fails to consume properly, returns two tokens); `user: "douglas adams"` (consumes, but two tokens) - which also explains why symbolic shorthands like "#" and "@" and no spaces are probably the "lesser evil" since the usage is more or less consistent and familiar to users. 
  * a more conservative implementation requires an extra "special" argument anywhere in the supplied parameters for a command to switch the token resolution on, e.g. `/bot addusers @johnnywhoops into #muchadoaboutnothing resolve`, `/bot createconversation resolve @jack @melissa` - i'm actually rather amenable to this implementation, as long as the argument is sufficiently unique, reasonably easy enough to remember, and not too verbose as to interrupt command flow.

as to "documented helper methods" - [`convfilter`](https://github.com/hangoutsbot/hangoutsbot/wiki/CONVID-Commands) and its [underlying function](https://github.com/hangoutsbot/hangoutsbot/wiki/Permanent-Memory#accessing-conversations-list) has been around for more than a year, and so far I haven't seen any external plugin make use of them ;P on a more serious note, based on this, it would probably be better to enforce the usage whether strongly (everywhere, always-on) or weakly (toggleable)

i like the point on user resolution having an optional conversation id, and any adaption should include this - personally, i would use it to prioritise a single user when doing the matching (if more than one match is found), rather than as a hard filter because it is assumed that this resolution would be intended more for botmins than normal users.

i have also given additional thought to making token resolution extensible/customisable to accommodate plugin developers who desire their own token match patterns (e.g. `@marylamb@`,  `@@bopeep`) or perhaps their own aliasing system as per #827

**Comment by endofline** [comment]
commit 6097921 turns the original example into any of the following:
```
/bot adduser resolve @patti into #bluegrass
/bot adduser @patti into #bluegrass resolve
/bot adduser resolve @patti into resolve #bluegrass

note: you only need one "resolve" anywhere in the parameter list after the command, 
it will not be seen by the actual addusers command
```
will work **as long as**:
* there is only one "patti" that the bot knows, and no other "accidentally" matching user with names like "pat tilapia" or "p atticus"
* bluegrass is a unique title fragment from "blue grass" or "bluegrass" and is an actual group
* (for now), the actual command doesn't need the keyword "resolve" - easily fixable if there is any, but just thought to add it here for the sake of completeness ;P if the command really needs the keyword, you can escape the resolve with by enclosing it in quotes `"resolve"` which shlex (and the `resolve` keyword detection for name/conv resolution) will then ignore

**Comment by endofline** [comment]
latest experimental changes ([diff](https://github.com/hangoutsbot/hangoutsbot/compare/v3.0...exp/eol-resolveids)):

* change of default trigger keyword to more unique `+resolve`, can be overridden via `config.json`
* addition of plugin-registered custom argument preprocessor groups - allowing plugin devs to add their own special token resolution, with [example plugin](https://github.com/hangoutsbot/hangoutsbot/blob/8d92f06da760104d66a35eb38c6ee9f758d10789/hangupsbot/plugins/_example/example_argpreprocessor.py) (*developer note: missing the `r` for the raw regex but works*)
* left-to-right processing of "trigger keyword" with botmin ability to select specific pre-processor groups for more specific token resolution e.g. 
  ```
  /bot <command> +resolve:custom1,custom2 @@test +resolve:custom2 #test# #test2#
  ``` 
  * `+resolve` uses in-built preprocessors and all other custom groups
  * `+resolve:0`, `+resolve:false`, `+resolve:off` turns off resolution for subsequent tokens
* all operations should be case-insensitive (although more testing may be required to make sure)

basic usage - the original example is now:
```
/bot adduser +resolve @patti into #bluegrass

note: place the trigger keyword immediately after the 
command now that left-to-right processing is enabled
```

**Comment by endofline** [comment]
for testers:
```
/bot convecho #here @somename #somechannel
```
works well for seeing how the replacement works

**Comment by pleasantone** [comment]
Great work, but I strongly recommend defaulting resolve to on. It's more important to cover the usual operational flow than to make everyone do more work for the rare-if-ever case.

In this case UX far outweighs perfect backwards compatibility.

**Comment by endofline** [comment]
works as expected:
```
/bot adduser @patti into #bluegrass
/bot convecho #here -resolve @somename #somechannel
/bot convecho #here @somename #somechannel
```

**Comment by endofline** [comment]
since there seems to be no additional suggestions on this, i've gone ahead and made some preliminary documentation to copy/paste into the wiki at a later point in time should this PR make it into v3.0 :)

---

# auto-resolution of conversation and user id

As of **Framework 3.0**, you can use specially-formatted command arguments `#conversation` and `@user` to search and map a single conversation/user:

```
#here
```
* shortcut reference that resolves to the current conversation ID where the command was issued

```
#conversationtitle
```
* resolves to a single GROUP conversation matching PART OF A CONVERSATION TITLE
* matching ignores spaces and case
> `#bottest` would resolve to a conversation bearing the name "**Bot Test**ing". If more than one conversation title matches this condition (e.g. there are two conversations with names "**Bot Test**ing" and "**Bot Test** 2", the bot will output an error message and stop further processing.

```
#nicknameorusername
```
* resolves to a single hangouts user matching EXACTLY THE NICKNAME, or PART OF A FULL NAME
* matching ignores spaces and case
* search will be performed within the current members of the conversation group where the command is issued, and will be automatically expanded to all users that the bot has encountered if no matches in the current conversation
> `@johnboy` would resolve to a user with nickname `johnboy` (set by `/bot setnickname`). If the nickname does not exist, then it would resolve to a user with a partially-matching full name (e.g. "**John Boy**chuck". If both users exist, then the user with the nickname will be prioritised. If there are no matching nicknames, and more than one user is returned due to partial matches of their full names "**John Boy**chuck" and "**John Boy**leyn", the bot will output an error message and stop further processing.

## advanced usage

### escaping strings

You can escape the specially formatted arguments with the backlash (`\#blahblahblah`) or by enclosing the entire argument with quotes (`"@usernobody"`) if you require the literal strings for whatever reason.

Note: Please also see the next sub-section on using trigger keywords

### trigger keywords to modify auto-resolution behaviour inline

The default trigger keyword is `resolve` and can be changed in `config.json`. There is a "switch on" trigger and a "switch off" trigger format, represented by `+resolve` (prefixed by `+` symbol) and `-resolve` (prefixed by `-` symbol).

Argument processing is performed from left-to-right. Therefore, adding a `-resolve` anywhere in a supplied command will prevent any further resolution to the right of trigger. Example:

```
/bot convecho #here -resolve #here
  --> outputs the literal string "#here" to the current conversation
```

Plugins can add extra auto-resolution behaviours beyond the `#conv` and `@user` formats which are part of the supplied `inbuilt` resolvers group. These customised formats and processing can be explicitly switched on/off using a combination of trigger terms. Example:

 ```
/bot convecho #here +resolve:doublehash ##here
  --> inbuilt resolution applied on "#here"
  --> custom resolution "doublehash" applied on "##here" (and subsequent arguments)

/bot convecho #here -resolve:inbuilt #here
  --> inbuilt resolution applied on first "#here"
  --> no inbuilt resolution applied on first "#here", any other custom group applied
```

### global auto-resolution settings

The following `config.json` directives are available:

```
"commands.preprocessor.trigger": "resolve"
```
* allows you to change the default trigger keyword
* please ensure that the word is unique enough not to clash with actual plugin parameters

```
"commands.preprocessor.explicit": false
```
* by default, auto-resolution is always on, and all auto-resolution groups (including custom ones defined by plugins) will be applied to any incoming command
* explicitly setting this value to `true` will switch auto-resolution to on-demand, requiring that +resolve be supplied as part of the command parameters before any auto-resolution is performed 

### customising auto-resolution via plugins

Internally, all resolvers must be part of a "resolver group" - for example, the `@user` and `#conv` resolvers are part of the `inbuilt` resolver group.

Plugin developers can add their own resolver groups to the command handler with their own special processing. These plugins must register the custom resolver group using the following pattern:

```
import plugins

plugins.register_commands_argument_preprocessor_group( "<groupname>", <resolver dict> )

<resolver_dict> = { r"<regex pattern>" : <replacement function>,
                    r"<regex pattern>" : <replacement function> }

  note: if you need to preserve dictionary key ordering, use collections.OrderedDict

<replacement function> = def replace_token( token, external_context )

  where:
    token = the raw token matched by the regex pattern
    external_context = source event

  should return:
    "<replaced token>" - successful replacement
                         skip remaining patterns
                         proceed to next argument
    False - argument will remain unchanged
            proceed to next pattern in same resolver group with same argument

  throw exception to indicate failure and the command should not be executed
```

**Comment by Terrance** [comment]
Changes have been merged, and no further discussion over there, so I'll go ahead and close this.
