### ISSUE TITLE
Delay @ mentions a few seconds, don't @ mention someone who has already read the message

### ISSUE THREAD

**Issue by pleasantone** [hangoutsbot/hangoutsbot#849]
Received a valid complaint from a user about @mentions....

"The problem that I have with @ mentions is that people misuse them as conversation rather than summoning.  I don't think bots should summon if you've been active in the hangout in the last X minutes."

While I don't agree about the last X minutes, but it seems reasonable to me that @mentions should be put on a queue for say, 15 seconds, and when those 15 seconds are up, check the target's watermark before sending them the message.  If they've caught up in the hangout, there is absolutely no reason to spam them with more crap.

**Comment by pleasantone** [comment]
Later suggestion -- "I kind of see your point but I don't think 15 seconds is enough.  Two minutes would be more like it.   Maybe two minutes if they have been active in the last X minutes, 15 seconds otherwise?" ...

The point is, some hangouts, like general chit-chat, or if someone has been gone forever, there is no need to delay the check.  But you can also get hangouts where you want to @ someone FAST and have them get the message with minimal delay.  Any solution we come up with should have heurstics in it to figure out "does it reduce spam if we delay?  if not, then send it right away" vs. trying to balance fast vs slow notification.

**Comment by jimsug** [comment]
I've considered this before and what I've thought about doing (which I haven't actually tried yet, so take it as is) is: for each conversation/user/convuser record/monitor a mean time to read. Then choose some arbitrary number and delay notifications by some inverse relationship unless the user reads the message in the meantime.

For example, taking convusers as the measure, for a conversation where a user usually reads messages fairly quickly, delay messages longer, because they'll probably check messages soon enough anyway and it'll reduce spam. 

In the same conversation, if a user usually reads messages after a long time, send the notification after one or two seconds, as they will probably otherwise not read the message soon.

And, in all cases, delay the notification by a small arbitrary amount - 2-5 seconds, I'd say - so that if users are actively reading that conversation, they won't get unnecessary mention notifications.

There was another thing that I'd considered which might be useful - an admin/tag-only @!mention, which would immediately deliver notifications regardless of this.

**Comment by pleasantone** [comment]
Contrapositive, if we implement this, do we mess up the situation where user has multiple instances of hangouts running? They might never receive an @ if they left it running on the desktop and walked off.

**Comment by jimsug** [comment]
> Contrapositive, if we implement this, do we mess up the situation where user has multiple instances of hangouts running? They might never receive an @ if they left it running on the desktop and walked off.

Yeah, I was going to say something about this. Are you aware of the phenomenon whereby people seem to read messages immediately after they are sent, at all hours of the day. I don't _think_ they've just left Hangouts open on the desktop but they might've.

I can't really think of a good way to distinguish this from people who are actively reading messages.

**Comment by endofline** [comment]
sidenote: based on previous testing on v2, watermarks don't fire instantaneously - they may take up to 10 seconds be registered on hangups; and occasionally go missing

**Comment by endofline** [comment]
simplest implementation would be a fixed timeout for every mention, set up an async task with a delay of 15 seconds. at 15 seconds, check whether the watermark for the target user in a conv has advanced beyond the original timestamp of the event. if yes, suppress the mention. 

this can be expanded into a look-behind as well, that is: immediately suppress the mention if the difference of the event timestamp and the last user-conv watermark event is within 10 seconds of each other.

personally, i consider this a special use-case for mentions because i'm quite sure nobody gets it right in other chats like slack, telegram, whatsapp etc (correct me if i'm wrong), so it will be a feature that must be enabled explicitly.

**Comment by jimsug** [comment]
Hmm. I want to know more about how some users might be reading messages instantaneously, though. If watermarks go missing, that's not a real problem - the behaviour will be as it is now, except that there will be a delay in sending mentions.

But for users whose watermarks constantly update immediately, any implementation discussed thus far would prevent them from ever receiving mentions, which is not good.

**Comment by endofline** [comment]
i'll test this instant-read further (i've noticed that it seems to occur more often with users with android wear running). you can also examine it further by enabling `_unittest.unittest_statusevents` in your config.json and observing the status event stream in for a test conversation

**Comment by jimsug** [comment]
Oh Android Wear! Could it be Apple Watch that's doing it for iOS users?
