### ISSUE TITLE
Re-add LICENSE?

### ISSUE THREAD

**Issue by pieps** [hangoutsbot/hangoutsbot#964]
I'd love to contribute to this project (in particular, bring the Slack integrations up to speed), but my employer requires a GPL* or LGPL* license for me to be able to do so.

It looks like the license was previously GPLv2 - any chance we could re-add it as such?

**Comment by Terrance** [comment]
I'm unsure entirely what happened here -- the license was temporarily lost (8938645), then bumped from GPLv2 to GPLv3 (00281a0) after it was restored, but then removed again (6d99d64) after it was noted that a license change would require approval from the previous code owner.  I don't see why it wasn't reverted to v2 at this point.

The result is we've now had the repository operating without any license for the last 3 years, during which time we've had a lot of additional contributors.  As I understand it, they would all now have to agree to their changes being licensed under GPL?

**Comment by pieps** [comment]
I'm no license expert, but given that any license changes would require previous code owner approval, I'd assume that the lack of an explicit license in the project is immaterial, as the previous owner's license would still apply.

Again though, I have no expertise in this regard, and I do have a vested interest in the GPLv2 license being restored, as my employer doesn't allow me to contribute to unlicensed or AGPL projects.

**Comment by Terrance** [comment]
Having spent some time investigating this with a couple other folks, the consensus seems to be that removing the license was invalid as derivative works must also be GPL-licensed, but also because we accepted contributions under v3 we're now tied to that (v3 being stricter, i.e. stronger freedoms, than v2, but otherwise backwards-compatible).

As such, I'll restore the GPLv3 license as it was before the removal.

**Comment by pieps** [comment]
GPLv3 works for me. Thanks!
